name: Build and Publish

on:
  push:
    branches:
      - stable
      - alpha

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore --warnaserror

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Pack
        run: |
          dotnet pack NetCord -c Release --no-build
          dotnet pack NetCord.Services -c Release --no-build
          dotnet pack Hosting/NetCord.Hosting -c Release --no-build
          dotnet pack Hosting/NetCord.Hosting.Services  -c Release --no-build
          dotnet pack Hosting/NetCord.Hosting.AspNetCore -c Release --no-build

      - name: Publish
        run: |
          dotnet nuget push NetCord/bin/Release/NetCord.nupkg -k ${{ secrets.NUGET_API_KEY }} -n -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push NetCord.Services/bin/Release/NetCord.Services.nupkg -k ${{ secrets.NUGET_API_KEY }} -n -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push Hosting/NetCord.Hosting/bin/Release/NetCord.Hosting.nupkg -k ${{ secrets.NUGET_API_KEY }} -n -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push Hosting/NetCord.Hosting.Services/bin/Release/NetCord.Hosting.Services.nupkg -k ${{ secrets.NUGET_API_KEY }} -n -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push Hosting/NetCord.Hosting.AspNetCore/bin/Release/NetCord.Hosting.AspNetCore.nupkg -k ${{ secrets.NUGET_API_KEY }} -n -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Build Documentation
        working-directory: Documentation
        run: |
          dotnet tool install docfx -g --version 2.75.3
          npm install
          npm run build

      - name: Deploy Documentation
        uses: appleboy/scp-action@v0.1.3
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          source: Documentation/_site
          strip_components: 2
          target: ~/NetCord/html
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: |
            NetCord/bin/Release
            NetCord.Services/bin/Release
            Hosting/NetCord.Hosting/bin/Release
            Hosting/NetCord.Hosting.Services/bin/Release
            Hosting/NetCord.Hosting.AspNetCore/bin/Release

      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Documentation Artifacts
          path: Documentation/_site
